// <auto-generated />
using System;
using Hospital.Repository.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hospital.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181213205610_Update2")]
    partial class Update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hospital.Model.Entities.Doctor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<long>("HarmonogramId");

                    b.Property<long>("SpecializationId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("HarmonogramId")
                        .IsUnique();

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Doctors");

                    b.HasData(
                        new { Id = 1L, Created = new DateTime(2018, 12, 13, 20, 56, 9, 569, DateTimeKind.Utc), HarmonogramId = 1L, SpecializationId = 1L, UserId = "9f2cfdcb-9f4d-4d65-a81c-43deacf27741" }
                    );
                });

            modelBuilder.Entity("Hospital.Model.Entities.Harmonogram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<TimeSpan>("FridayEnd");

                    b.Property<TimeSpan>("FridayStart");

                    b.Property<TimeSpan>("MondayEnd");

                    b.Property<TimeSpan>("MondayStart");

                    b.Property<TimeSpan>("ThursdayEnd");

                    b.Property<TimeSpan>("ThursdayStart");

                    b.Property<TimeSpan>("TuesdayEnd");

                    b.Property<TimeSpan>("TuesdayStart");

                    b.Property<TimeSpan>("WednesdayEnd");

                    b.Property<TimeSpan>("WednesdayStart");

                    b.HasKey("Id");

                    b.ToTable("Harmonograms");

                    b.HasData(
                        new { Id = 1L, Created = new DateTime(2018, 12, 13, 20, 56, 9, 571, DateTimeKind.Utc), FridayEnd = new TimeSpan(0, 0, 0, 0, 0), FridayStart = new TimeSpan(0, 0, 0, 0, 0), MondayEnd = new TimeSpan(0, 0, 0, 0, 0), MondayStart = new TimeSpan(0, 0, 0, 0, 0), ThursdayEnd = new TimeSpan(0, 0, 0, 0, 0), ThursdayStart = new TimeSpan(0, 0, 0, 0, 0), TuesdayEnd = new TimeSpan(0, 0, 0, 0, 0), TuesdayStart = new TimeSpan(0, 0, 0, 0, 0), WednesdayEnd = new TimeSpan(0, 0, 0, 0, 0), WednesdayStart = new TimeSpan(0, 0, 0, 0, 0) }
                    );
                });

            modelBuilder.Entity("Hospital.Model.Entities.Medicament", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Medicaments");
                });

            modelBuilder.Entity("Hospital.Model.Entities.Nurse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<long>("NurseSpecializationId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("NurseSpecializationId");

                    b.HasIndex("UserId");

                    b.ToTable("Nurses");

                    b.HasData(
                        new { Id = 1L, Created = new DateTime(2018, 12, 13, 20, 56, 9, 578, DateTimeKind.Utc), NurseSpecializationId = 1L, UserId = "9f2cfdcb-9f4d-4d65-a81c-43deacf27741" }
                    );
                });

            modelBuilder.Entity("Hospital.Model.Entities.NurseSpecialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("NurseSpecializations");

                    b.HasData(
                        new { Id = 1L, Created = new DateTime(2018, 12, 13, 20, 56, 9, 588, DateTimeKind.Utc), Name = "Onkologiczna" }
                    );
                });

            modelBuilder.Entity("Hospital.Model.Entities.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Patients");

                    b.HasData(
                        new { Id = 1L, Created = new DateTime(2018, 12, 13, 20, 56, 9, 571, DateTimeKind.Utc), UserId = "9f2cfdcb-9f4d-4d65-a81c-43deacf27742" }
                    );
                });

            modelBuilder.Entity("Hospital.Model.Entities.Prescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DueDate");

                    b.Property<long>("VisitId");

                    b.HasKey("Id");

                    b.HasIndex("VisitId")
                        .IsUnique();

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Hospital.Model.Entities.PrescriptionMedicament", b =>
                {
                    b.Property<long>("PrescriptionId");

                    b.Property<long>("MedicamentId");

                    b.HasKey("PrescriptionId", "MedicamentId");

                    b.HasIndex("MedicamentId");

                    b.ToTable("PrescriptionMedicaments");
                });

            modelBuilder.Entity("Hospital.Model.Entities.Specialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new { Id = 1L, Created = new DateTime(2018, 12, 13, 20, 56, 9, 572, DateTimeKind.Utc), Name = "Dentysta" }
                    );
                });

            modelBuilder.Entity("Hospital.Model.Entities.Vaccine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<string>("Description");

                    b.Property<string>("Dosage");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Vaccines");

                    b.HasData(
                        new { Id = 1L, Created = new DateTime(2018, 12, 13, 20, 56, 9, 579, DateTimeKind.Utc), Description = "Grypa", Dosage = "(X ml/kg ", Name = "VaxigripTetra" }
                    );
                });

            modelBuilder.Entity("Hospital.Model.Entities.VaccineApplied", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateTime");

                    b.Property<long>("NurseId");

                    b.Property<long>("PatientId");

                    b.Property<long>("VaccineId");

                    b.HasKey("Id");

                    b.HasIndex("NurseId");

                    b.HasIndex("PatientId");

                    b.HasIndex("VaccineId");

                    b.ToTable("VaccineApplieds");
                });

            modelBuilder.Entity("Hospital.Model.Entities.Visit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<long>("DoctorId");

                    b.Property<long>("PatientId");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("Hospital.Model.Identity.ApplicationIdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Hospital.Model.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<int>("Gender");

                    b.Property<bool>("IsActive");

                    b.Property<DateTime>("LastLoginTime");

                    b.Property<string>("LastName")
                        .HasMaxLength(30);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NIP")
                        .HasMaxLength(30);

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PESEL")
                        .HasMaxLength(20);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20);

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10);

                    b.Property<string>("Province")
                        .HasMaxLength(30);

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("Street")
                        .HasMaxLength(30);

                    b.Property<string>("SystemRoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new { Id = "9f2cfdcb-9f4d-4d65-a81c-43deacf27741", AccessFailedCount = 0, City = "Toruń", ConcurrencyStamp = "ed79543f-6875-4bc5-9c70-e0cc07fcb76f", Created = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), DateOfBirth = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), Email = "doctor@test.com", EmailConfirmed = false, FirstName = "Marian", Gender = 0, IsActive = false, LastLoginTime = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), LastName = "Nowak", LockoutEnabled = false, PESEL = "11111111111", PasswordHash = "AQAAAAEAACcQAAAAECKLtts8yfs643jZ79ss7Oj7shA9VVpWxwCwDN361Rn93O6aHWvMzquScKdHxFdLQQ==", PhoneNumber = "123456789", PhoneNumberConfirmed = false, PostalCode = "87-100", Province = "Kujawsko Pomorskie", Street = "Szeroka 10", SystemRoleName = "Doctor", TwoFactorEnabled = false, UserName = "doctor@test.com" },
                        new { Id = "9f2cfdcb-9f4d-4d65-a81c-43deacf27742", AccessFailedCount = 0, City = "Toruń", ConcurrencyStamp = "ee04850c-4fa2-419f-a4aa-9bc4489cfd1c", Created = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), DateOfBirth = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), Email = "patient@test.com", EmailConfirmed = false, FirstName = "Piotr", Gender = 0, IsActive = false, LastLoginTime = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), LastName = "Kiepski", LockoutEnabled = false, PESEL = "11111111112", PasswordHash = "AQAAAAEAACcQAAAAECKLtts8yfs643jZ79ss7Oj7shA9VVpWxwCwDN361Rn93O6aHWvMzquScKdHxFdLQQ==", PhoneNumber = "123456780", PhoneNumberConfirmed = false, PostalCode = "87-100", Province = "Kujawsko Pomorskie", Street = "Szeroka 10", SystemRoleName = "Patient", TwoFactorEnabled = false, UserName = "patient@test.com" },
                        new { Id = "9f2cfdcb-9f4d-4d65-a81c-43deacf27743", AccessFailedCount = 0, City = "Toruń", ConcurrencyStamp = "8906892e-779c-4720-9bc4-584e111d9e7e", Created = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), DateOfBirth = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), Email = "nurse@test.com", EmailConfirmed = false, FirstName = "Katarzyna", Gender = 1, IsActive = false, LastLoginTime = new DateTime(2018, 12, 13, 20, 56, 9, 565, DateTimeKind.Utc), LastName = "Boczek", LockoutEnabled = false, PESEL = "11111181112", PasswordHash = "AQAAAAEAACcQAAAAECKLtts8yfs643jZ79ss7Oj7shA9VVpWxwCwDN361Rn93O6aHWvMzquScKdHxFdLQQ==", PhoneNumber = "123256780", PhoneNumberConfirmed = false, PostalCode = "87-100", Province = "Kujawsko Pomorskie", Street = "Długa 11", SystemRoleName = "Nurse", TwoFactorEnabled = false, UserName = "nurse@test.com" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Hospital.Model.Entities.Doctor", b =>
                {
                    b.HasOne("Hospital.Model.Entities.Harmonogram", "Harmonogram")
                        .WithOne("Doctor")
                        .HasForeignKey("Hospital.Model.Entities.Doctor", "HarmonogramId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hospital.Model.Entities.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hospital.Model.Identity.ApplicationUser", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("Hospital.Model.Entities.Doctor", "UserId");
                });

            modelBuilder.Entity("Hospital.Model.Entities.Nurse", b =>
                {
                    b.HasOne("Hospital.Model.Entities.NurseSpecialization", "NurseSpecialization")
                        .WithMany("Nurses")
                        .HasForeignKey("NurseSpecializationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hospital.Model.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Hospital.Model.Entities.Patient", b =>
                {
                    b.HasOne("Hospital.Model.Identity.ApplicationUser", "User")
                        .WithOne("Patient")
                        .HasForeignKey("Hospital.Model.Entities.Patient", "UserId");
                });

            modelBuilder.Entity("Hospital.Model.Entities.Prescription", b =>
                {
                    b.HasOne("Hospital.Model.Entities.Visit", "Visit")
                        .WithOne("Prescription")
                        .HasForeignKey("Hospital.Model.Entities.Prescription", "VisitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hospital.Model.Entities.PrescriptionMedicament", b =>
                {
                    b.HasOne("Hospital.Model.Entities.Medicament", "Medicament")
                        .WithMany("PrescriptionMedicaments")
                        .HasForeignKey("MedicamentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hospital.Model.Entities.Prescription", "Prescription")
                        .WithMany("PrescriptionMedicaments")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hospital.Model.Entities.VaccineApplied", b =>
                {
                    b.HasOne("Hospital.Model.Entities.Nurse", "Nurse")
                        .WithMany("VaccineApplieds")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hospital.Model.Entities.Patient", "Patient")
                        .WithMany("VaccineApplieds")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hospital.Model.Entities.Vaccine", "Vaccine")
                        .WithMany("VaccineApplieds")
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hospital.Model.Entities.Visit", b =>
                {
                    b.HasOne("Hospital.Model.Entities.Doctor", "Doctor")
                        .WithMany("Visits")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hospital.Model.Entities.Patient", "Patient")
                        .WithMany("Visits")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Hospital.Model.Identity.ApplicationIdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Hospital.Model.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Hospital.Model.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Hospital.Model.Identity.ApplicationIdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hospital.Model.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Hospital.Model.Identity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
